### PR TITLE
Fixing linting error

### PR DESCRIPTION
**Pull request by igor-ribeiiro**
```npm run lint``` was giving errors. So I ran ```npm run prettier``` and ```npm run lint:fix``` to solve.

Now there are no lint issues

Tests:
- Tested with ```npm run test```

### CODE REVIEW

**Comment by akrantz** [comment]
You don't need the package-lock.json changes. The other changes are fine.

**Comment by igor-ribeiiro** [comment]
> You don't need the package-lock.json changes. The other changes are fine.

Why is not better for me to update the package-lock.json file?? It simply goes and updates the packages versions, so it looks good for it to be updated

**Comment by akrantz** [comment]
It's not related to what you are fixing. It's better for a PR to be targeted to a specific thing. 

Also, packages are updated all the time, and the point of the package-lock file is to stay on consistent versions until a change to the package dependencies are needed, typically when you install, update, or remove a package. We need to make package updates periodically, but it would be better for this to be done separately. Ideally, we would automate this.

**Comment by igor-ribeiiro** [comment]
> It's not related to what you are fixing. It's better for a PR to be targeted to a specific thing.
> 
> Also, packages are updated all the time, and the point of the package-lock file is to stay on consistent versions until a change to the package dependencies are needed, typically when you install, update, or remove a package. We need to make package updates periodically, but it would be better for this to be done separately. Ideally, we would automate this.

Sure, I just reverted the change

**Comment by akrantz** [comment]
When I checkout your branch and run prettier, it undoes your changes here. Are we using different rules somehow?

**Comment by igor-ribeiiro** [comment]
> When I checkout your branch and run prettier, it undoes your changes here. Are we using different rules somehow?

That's weird. I literally ran this command with the repository fresh (with my virtual desktop). 
But anyway the CI tests are not passing, as if no change was made. I will check that problem still.

**Pull request closed without merging**
