### PR TITLE
Remove browser launch and task json

### PR DESCRIPTION
**Pull request by millerds**
Thank you for your pull request!  Please provide the following information.

---

**Change Description**:
Current functionality of the sideloading cli doesn't work with vs code launch config options.  Sideloading needs to be updated in order to support it.  Removing for the time being.

1. **Do these changes impact any *npm scripts* commands (in package.json)?** (e.g., running 'npm run start')
Nol

2. **Do these changes impact *VS Code debugging* options (launch.json)?**
Yes.  Removing some options that don't work.

3. **Do these changes impact *template output*?** (e.g., add/remove file, update file location, update file contents)
Yes.  VS code support files have been updated.

4. **Do these changes impact *documentation*?** (e.g., a tutorial on https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins)
Possibly . . . if there is anything the specifically refers to debugging office online then it will need to be looked at.

If you answered yes to any of these please do the following:
    > Include 'Rick-Kirkham' in the review
    > Make sure the README file is correct

**Validation/testing performed**:

    Describe manual testing done.

### CODE REVIEW

**Comment by Rick-Kirkham** [comment]
@millerds Is this the only template that is affected? Do we have these same launch/tasks in other templates?

**Comment by millerds** [comment]
> @millerds Is this the only template that is affected? Do we have these same launch/tasks in other templates?

This will get merged into the other templates as well.

**Review by Rick-Kirkham — APPROVED** [review]

**Comment by Rick-Kirkham** [comment]
> > @millerds Is this the only template that is affected? Do we have these same launch/tasks in other templates?
> 
> This will get merged into the other templates as well.

Got it. There is actually only one section of one article in the docs which uses this option. I'll remove that from the article.

**Comment by akrantz** [comment]
What's the rationale for removing this?

**Comment by millerds** [comment]
We talked in person . . . but essentially there is a conflict between the launch config needing the URL and the office-addin-debugging web cli needing the document URL and both trying to launch the browser.  My investigation shows that it's been broken for a while and we haven't seen complaints so I'm removing the launch config to give us time to come up with a solution to the conflict.

**Comment by millerds** [comment]
Can I get and OP DevX review?

**Review by Adrian-MSFT — APPROVED** [review]

**Review by kwame-ansong — APPROVED** [review]

**Pull request merged**
