### PR TITLE
AppDomain in manifest should include the protocol

### PR DESCRIPTION
**Pull request by akrantz**

### CODE REVIEW

**Comment by akrantz** [comment]
I also formatted the XML which made some minor updates to the manifest files.

**Comment by akrantz** [comment]
The other option would be to remove `<AppDomains>...</AppDomains>` altogether since it is not required by default.

**Comment by TCourtneyOwen** [comment]
I see the CI loop passed. Did you have to manually fix the webview issue I mentioned on the VM to unblock the tests or has this issue magically resolved itself?

**Review by TCourtneyOwen — APPROVED** [review]

**Comment by akrantz** [comment]
@TCourtneyOwen  The 1903 build failed. I didn't do anything regarding the CI loop. Can you see about getting this all passing so we can merge it?

**Comment by TCourtneyOwen** [comment]
I manually fixed the VMs this morning, reran the job and it just passed

**Pull request merged**
