### PR TITLE
Remove confusing React stuff from this non-React project template

### PR DESCRIPTION
**Pull request by Rick-Kirkham**
I've tested this and the project works fine with these changes. This will make the project less confusing to developers who are poking around in the config files, which they might be doing either for learning or to modify the project. 

The only change I intentionally made to package.json is to delete this line:

"ts-loader": "^9.2.5",

But I see a lot of other deletions in the diff. Maybe one of you guys can explain that.

This will fix [156](https://github.com/OfficeDev/Office-Addin-TaskPane/issues/156)

### CODE REVIEW

**Review by akrantz — CHANGES_REQUESTED** [review]
You have proposed a lot of changes that are not in line with how these templates work. For example, don't remove convert-to-single-host, as this breaks yo office.  All of the other changes to the engines, scripts are also necessary. All of the dependencies you are removing are necessary.

Furthermore, this template is merged into Office-Addin-TaskPane-React and as I mentioned before, unless there is actually a problem shown by having the .tsx extension, we should not be making these changes.

**Comment by Rick-Kirkham** [comment]
> You have proposed a lot of changes that are not in line with how these templates work. For example, don't remove convert-to-single-host, as this breaks yo office. All of the other changes to the engines, scripts are also necessary. All of the dependencies you are removing are necessary.
> 
> Furthermore, this template is merged into Office-Addin-TaskPane-React and as I mentioned before, unless there is actually a problem shown by having the .tsx extension, we should not be making these changes.

Thanks for the feedback @akrantz. You actually responded before I could finish creating the PR comment.  
I don't understand all the deletions in the package.json, so I need some help with this. E.g., I didn't intend to remove convert-to-single-host. I'll see if I can fix this in another commit to the PR. 

If this template is merged into Office-Addin-TaskPane-React, then I think we should change this architecture so that the React-related things are only in the Office-Addin-TaskPane-React template. 

As I suggested in the Issue 156, there is a problem with the having React-related things in a non-React template: It is confusing to developers.

**Comment by akrantz** [comment]
We don't have React things in the non-React template. We just have the extension for both .ts and .tsx files. Is it just the file extension filter? We've never gotten feedback that this is confusing (other than for you). 

The ts-loader I believe is for type checking. Did you test out having errors in the TypeScript code so they are caught by the type checking? There are complex aspects to this and I don't even recall all of it. Unless there was a change with webpack 5 which eliminated the need for ts-loader, I'm pretty sure we should still include it. I could not tell easily from the webpack docs.

**Comment by Rick-Kirkham** [comment]
> We don't have React things in the non-React template. We just have the extension for both .ts and .tsx files. Is it just the file extension filter? We've never gotten feedback that this is confusing (other than for you).
> 
> The ts-loader I believe is for type checking. Did you test out having errors in the TypeScript code so they are caught by the type checking? There are complex aspects to this and I don't even recall all of it. Unless there was a change with webpack 5 which eliminated the need for ts-loader, I'm pretty sure we should still include it. I could not tell easily from the webpack docs.

I'll try the type-checking. Regardless of the result, I will delete this PR. I think it makes more sense for me to just raise the issue and leave implementing the fix to the developers.  

Being the customer's advocate is part of my job. If I find something confusing, there is a good chance that customers will too.

**Pull request closed without merging**
