### PR TITLE
Reveting rules change

### PR DESCRIPTION
**Pull request by igor-ribeiiro**
Reverting last changes to .eslintrc.json, given that they are not needed

### CODE REVIEW

**Review by akrantz — DISMISSED** [review]
@TCourtneyOwen you should pick this up and merge to the other templates.

**Comment by igor-ribeiiro** [comment]
The error is still happening because it is not using the latest version of office-addin-lint yet. It was only pushed one day ago and not published yet
Should I publish it so it can use that??

**Review by akrantz — CHANGES_REQUESTED** [review]
Run `npm outdated --long`. You'll notice that `eslint-config-office-addins` also needs to be updated. This is what actually has the defaults for the `endOfLine: auto` change, right?

**Comment by igor-ribeiiro** [comment]
> Run `npm outdated --long`. You'll notice that `eslint-config-office-addins` also needs to be updated. This is what actually has the defaults for the `endOfLine: auto` change, right?

The changes should be in Office-Addin-Lint as I just checked, but I updated the packaged anyway

**Review by akrantz — APPROVED** [review]

**Pull request merged**
