### PR TITLE
Test list fixes

### PR DESCRIPTION
**Pull request by igor-ribeiiro**
Testing end of line errors

### CODE REVIEW

**Review by TCourtneyOwen — APPROVED** [review]

**Comment by akrantz** [comment]
@TCourtneyOwen @igor-ribeiiro Was this change really neccessary? I thought the default was updated, and this was just a test to validate that it could be overwritten but wasn't intended to be merged.

**Comment by igor-ribeiiro** [comment]
> @TCourtneyOwen @igor-ribeiiro Was this change really neccessary? I thought the default was updated, and this was just a test to validate that it could be overwritten but wasn't intended to be merged.

I Think only the prettier file was not necessary (given that the adding should already fix the issue).
The rest were only lint fixes and could be merge fine

**Comment by akrantz** [comment]
Yes, I was referring to the .eslintrc.json change.

**Comment by igor-ribeiiro** [comment]
> Yes, I was referring to the .eslintrc.json change.

Just created a PR to revert the change to this file:
[https://github.com/OfficeDev/Office-Addin-TaskPane/pull/111](url)

**Pull request merged**
